#!/bin/sh
#
# Make batocera.conf specific values available to batocera-boot.conf
# in a very early boot stage process where the regular conf-file
# is not available.

# Only copy values on shutdown/reboot
[ "$1" = "stop" ] || exit 0

set --
keys="wifi.enabled wifi.ssid wifi.key"
n=2
while true; do
    ssid="$(/usr/bin/batocera-settings-get "wifi${n}.ssid")"
    [ -z "$ssid" ] && break
    keys="$keys wifi${n}.ssid wifi${n}.key"
    n=$((n + 1))
done
keys="$keys wifi.hidden.ssid wifi.hidden.key wifi.adhoc.ssid wifi.adhoc.key"
keys="$keys splash.screen.enabled system.timezone es.resolution system.hostname"
for key in $keys
do
    value="$(/usr/bin/batocera-settings-get "$key")" # in case it is empty, it must be set in the batocera-boot.conf file to erase any existing value
    if [ "$value" != "$(/usr/bin/batocera-settings-get -f /boot/batocera-boot.conf "$key")" ]
    then
        set -- "$@" "$key" "$value"
    fi
done

if [ $# -gt 0 ]
then
    mount -o remount,rw /boot
    /usr/bin/batocera-settings-set -f /boot/batocera-boot.conf "$@"
    mount -o remount,ro /boot
fi

exit $?
