advision:
  emulator: libretro
  core:     mame
flash:
  emulator: lightspark
  core:     lightspark
fmtowns:
  emulator: libretro
  core:     mame
lcdgames:
  emulator: libretro
  core:     mame
n64:
  emulator: libretro
  core:     mupen64plus-next
nds:
  emulator: libretro
  core:     melonds
ps2:
  emulator: libretro
  core:     play
plugnplay:
  emulator: libretro
  core:     mame
pdp1:
  emulator: libretro
  core:     mame
pv1000:
  emulator: libretro
  core:     mame
gamate:
  emulator: libretro
  core:     mame
crvision:
  emulator: libretro
  core:     mame
gamecom:
  emulator: libretro
  core:     mame
fm7:
  emulator: libretro
  core:     mame
gamepock:
  emulator: libretro
  core:     mame
apfm1000:
  emulator: libretro
  core:     mame
bbc:
  emulator: libretro
  core:     mame
adam:
  emulator: libretro
  core:     mame
gmaster:
  emulator: libretro
  core:     mame
astrocde:
  emulator: libretro
  core:     mame
ti99:
  emulator: libretro
  core:     mame
tutor:
  emulator: libretro
  core:     mame
coco:
  emulator: libretro
  core:     mame
archimedes:
  emulator: libretro
  core:     mame
socrates:
  emulator: libretro
  core:     mame
supracan:
  emulator: libretro
  core:     mame
vsmile:
  emulator: libretro
  core:     mame
xegs:
  emulator: libretro
  core:     mame
atom:
  emulator: libretro
  core:     mame
electron:
  emulator: libretro
  core:     mame
camplynx:
  emulator: libretro
  core:     mame
vgmplay:
  emulator: libretro
  core:     mame
vc4000:
  emulator: libretro
  core:     mame
gp32:
  emulator: libretro
  core:     mame
laser310:
  emulator: libretro
  core:     mame
cdi:
  emulator: libretro
  core:     same_cdi
